---
# tasks file for setup-apache-role

- name: Install httpd package
  yum:
    name: httpd
    state: installed
  when: ansible_os_family == "RedHat"
  notify: start httpd service

- name: Install apache2 package
  apt:
    name: apache2
    state: present
  when: ansible_os_family == "Debian"
  notify: start apache2 service

- name: copy index.html
  copy:
    src: /home/ansadmin/index.html
    dest: /var/www/html
    mode: 0666
